
  
 <!-- =============================================== -->

      <!-- This Code was Generated by CodeGeniter tool
    Developed by: Joemarie Amar
    Code by: Jeffrey Limbaga
    Date/Time code generated: April 08, 2016 17:13:56 -->
     
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1> Receiving Report<small></small> </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Masterfile</a></li>
            <li><a href="#">Unit</a></li>
          </ol>
        </section>


        <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Receiving Report List</h3>
            </div>
            <div class="box-body table-responsive">
              <div class="box box-success collapsed-box">
                <div class="box-header with-border">
                  <h3 class="box-title">Query Builder</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                  </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body" style="display: none;">
                  <div id="builder"></div>
                  <div class="btn-group" style="width:100%">
                    <input type="button" class="btn btn-warning reset" value="Reset" />
                    <input type="button" class="btn btn-primary parse-sql" value="Run" />
                  </div>
                  <textarea class="form-control sql-parsed" rows="1" id="sql-parsed" name="sql-parsed" style="display:none;"></textarea>
                </div><!-- /.box-body -->
              </div>
    
             
              <!--- Start of custom details-->
        
         
              <button class="btn btn-primary" id="btnPrint" onclick="add_new()"><i class="glyphicon glyphicon-plus"></i> Add</button>
              <button class="btn btn-info" id="btn2" onclick="archive()">Archive List</button>
 
                <table id="table_repository" class="table table-striped table-bordered table-hover" 
                        data-search="true" 
                        data-pagination="true"
                        data-show-export="true"
                        data-show-columns="true"
                        data-mobile-responsive="true"
                        data-sort-name = "dd"
                        data-sort-order = "desc"
                        data-check-on-init="true"
                        data-filter-control = "true"
                        data-page-list="[10, 25, 50, 100, ALL]">
                  <thead>
                    <tr>
                        <th data-field="rn"  data-sortable = "true"><abbr title="Reference Number">Reference No.</abbr></th>
                        <th data-field="company"  data-sortable = "true"><abbr title="Reference Number">Company</abbr></th>
                        <th data-field="supp"  data-sortable = "true"><abbr title="Reference Number">Supplier</abbr></th>
                        <th data-field="dn"  data-sortable = "true"><abbr title="Document Number">Document No.</abbr></th>
                        <th data-field="dd">Document Date</th>
                        <th data-field="po"><abbr title="Purchase Order Number">PO No.</abbr></th>
                          <th data-field="item" data-visible="false">Item</th>
                        <th data-field="action"></th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
             <?php
          for ($i=0; $i<sizeof($privileges); $i++) { 
            if ($privileges[$i]->privilege_name == "repository_add") 
             {                
          echo '<div id="toolbar">
                  <button class="btn btn-success" onclick="add_repository()"><i class="glyphicon glyphicon-plus"></i> Add repository</button></a>
               </div>';     
             }
          }
        ?> 
           
              </div>

              <!-- JAVASCRIPT -->
              <script src="<?php echo base_url();?>assets/plugins/jQuery/jQuery-2.1.4.min.js"></script>
              <script src="<?php echo base_url();?>assets/plugins/bootstrap-table-develop/dist/bootstrap-table.js"></script>
              <script src="<?php echo base_url();?>assets/plugins/bootstrap-table-develop/dist/extensions/mobile/bootstrap-table-mobile.js"></script>
              <script src="<?php echo base_url();?>assets/plugins/bootstrap-table-develop/dist/extensions/export/bootstrap-table-export.js"></script>
              <script src="<?php echo base_url();?>assets/plugins/bootstrap-table-develop/dist/extensions/export/tableExport.js"></script>
              <script src="<?php echo base_url();?>assets/plugins/bootstrap-table-develop/dist/extensions/filter-control/bootstrap-table-filter-control.js"></script>

              <script type="text/javascript">
                <?Php $this->load->view('rr_gen_js');?>  
           </script>
           
          <!-- MODAL FORM -->
            <div class="modal fade" id="modal_form_repository" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h3 class="modal-title">Unit</h3>
                </div>
                <div class="modal-body form">
                  <form action="#" id="form_repository" class="form-horizontal">
                    <input type="hidden" value="" name="id"/> 
                    <div class="form-group">
  <label class="control-label col-md-3">Description</label>
  <div class="col-md-6">
    <input name="desc" placeholder="Enter repository Code" class="form-control" type="text" >
  </div>
</div>

<div class="form-group">
  <label class="control-label col-md-3">GLcode</label>
  <div class="col-md-6">
    <input name="glcode" placeholder="Enter repository Desc" class="form-control" type="text" >
  </div>
</div>

                  </form>
                    </div>
                    <div class="modal-footer">
                      <button type="button" id="btnSave" onclick="save_repository()" class="btn btn-primary">Save</button>
                      <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>
                  </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
           
            </div>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      