
                //This Code was Generated by CodeGeniter tool
                //Developed by: Joemarie Amar
                //Date/Time code generated: April 08, 2016 17:13:56  
        
                var save_method; //for save method string
                var lctable_repository;
                var $lctable_repository = $('#table_repository');
                $(document).ready(function() {
                  $('#toolbar').find('select').change(function () {
                      $lctable_repository.bootstrapTable('refreshOptions', {
                          exportDataType: $(this).val()
                      });
                  });


                  repository_create_query_builder();
                  repositorylist();
                });

                function repositorylist()
                {
                   $('#btn1').addClass('hidden');
                       $('#btn2').removeClass('hidden');
                  $.ajax({
                    url : "<?php echo site_url('Receiving_report_generate/ajax_list')?>",
                    type: "POST",
                    dataType: "JSON",
                    success: function(data)
                    {    
                        var a = new Array();  
                        
                        for (x = 0; x < data.data.length; x++) {
                          a[x] = 
                          {
                             "rn": data.data[x][0],
                    "dn": data.data[x][1],
                             "dd": data.data[x][2], 
               "po": data.data[x][3],
               "action": data.data[x][4], 
               "company": data.data[x][5], 
               "supp": data.data[x][6], 
               "item": data.data[x][7], 
                          };
                        }
                        console.log(a);
                        $('#table_repository').bootstrapTable({ data: a });
                        $('#table_repository').bootstrapTable('load',a);
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                        alert('Error get data from ajax');
                    }
                  });
                }
                    function repositorylist2()
                {
                   $('#btn2').addClass('hidden');
                       $('#btn1').removeClass('hidden');
                  $.ajax({
                    url : "<?php echo site_url('Receiving_report_generate/ajax_list2')?>",
                    type: "POST",
                    dataType: "JSON",
                    success: function(data)
                    {    
                        var a = new Array();  
                        
                        for (x = 0; x < data.data.length; x++) {
                          a[x] = 
                          {
                             "rn": data.data[x][0],
                    "dn": data.data[x][1],
                             "dd": data.data[x][2], 
               "po": data.data[x][3],
               "action": data.data[x][4], 
               "company": data.data[x][5], 
               "supp": data.data[x][6], 
               "item": data.data[x][7], 
                          };
                        }
                        console.log(a);
                        $('#table_repository').bootstrapTable({ data: a });
                        $('#table_repository').bootstrapTable('load',a);
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                        alert('Error get data from ajax');
                    }
                  });
                }
                function repository_load_table_querybuilder()
                {                  
       
                  var query = $('#sql-parsed').val();
                  $.ajax({
                    url : "<?php echo site_url('Receiving_report_generate/ajax_list_querybuilder')?>",
                    type: "POST",
                    dataType: "JSON",
                    data: {query: query},
                    success: function(data)
                    {    
                        var a = new Array();  
                        
                        for (x = 0; x < data.data.length; x++) {
                          a[x] = 
                          {
                             "rn": data.data[x][0],
                                "dn": data.data[x][1],
                                         "dd": data.data[x][2], 
                           "po": data.data[x][3],
                           "action": data.data[x][4], 
                           "company": data.data[x][5], 
                           "supp": data.data[x][6], 
                          };
                        }
                        console.log(a);
                        $('#table_repository').bootstrapTable({ data: a });
                        $('#table_repository').bootstrapTable('load',a);
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                        alert('Error get data from ajax');
                    }
                  });
                }

            


             
 

                function repository_create_query_builder()
                {
                  var rules_basic = {
                    condition: 'AND',
                    rules: [{
                      "id": "inventoryCode"
                    }]
                  };

                  $('#builder').queryBuilder({
                    plugins: ['bt-tooltip-errors'],
                    filters: 
                    [
                      {id: 'inventoryCode',label: 'Inventory Code',type: 'string'},
                      {id: 'supplier',label: 'Supplier ',type: 'string'},
                      {id: 'description',label: 'Item Description ',type: 'string'},
                    ],
                    rules: rules_basic
                  });

                  // reset builder
                  $('.reset').on('click', function () {
                      $('#builder').queryBuilder('reset');
                      $(".json-parsed").empty();
                      $(".sql-parsed").empty();
                      repositorylist();
                  });

                  // get rules & SQL
                  $('.parse-sql').on('click', function () {
                      // SQL
                      var resSql = $('#builder').queryBuilder('getSQL', false);
                      $(".sql-parsed").html(resSql.sql);
                      repository_load_table_querybuilder();
                  });
                }

            function generate (id) {
                
                var win = window.open("<?php echo site_url('Receiving_report_generate/print_rr')?>/"+id, '_blank');
                win.focus();
            }

            function add_new () {
               location = "<?php echo site_url('Receiving_report')?>";
            }
            function archive () {
               location = "<?php echo site_url('Rr_archive')?>";
            }
             function edit_rr (id) 
                {
                  location="<?php echo site_url('Report_edit')?>?id="+id;
              }
            function delete_rr (id) 
            {
              if(confirm('Are you sure delete this data?'))
                {
                  // ajax delete data to database
                    $.ajax({
                      url : "<?php echo site_url('Receiving_report_generate/ajax_delete')?>/"+id,
                      type: "POST",
                      dataType: "JSON",
                      success: function(data)
                      {
                         //if success reload ajax table
                        $('#modal_form_Location').modal('hide');
                         repositorylist();
                      },
                      error: function (jqXHR, textStatus, errorThrown)
                      {
                          alert('Error adding / update data');
                      }
                  });
                   
                }
            }